### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by chisi21** [ElectroGamesYT/BankUI#1]
Add feature
• create account (pin bank, type account like silver, gold, platinum. and each account has a different limit) 
• tax (tax for each account type) 
• transaction history
• upgrade bank (like silver to gold, etc) 

Just suggestion :D
Thanks

**Comment by ElectroGamesDev** [comment]
I can forsure consider adding Tax and Transaction History!
Thanks for the suggestion.

**Comment by ElectroGamesDev** [comment]
I have added a Transaction Log and Interest. I do not plan on adding any of these other suggestions, sorry. Feel free to open another issue if you have more suggestions though! :D

**Comment by chisi21** [comment]
> I have added a Transaction Log and Interest. I do not plan on adding any of these other suggestions, sorry. Feel free to open another issue if you have more suggestions though! :D

no problem bro, thanks a lot :D im appreciate....
