### ISSUE TITLE
Update to 4.0.0+

### ISSUE THREAD

**Issue by DrGuile** [ElectroGamesYT/BankUI#12]
can you pls update this to 4.0.0+ as this is useless without it as the economyAPI is in version 4.0.0-4.0.3

**Comment by BhawaniTheKing** [comment]
Yes He Right Plz Update That To Api : 4.0.0

**Comment by ElectroGamesDev** [comment]
Yes, I plan to.

**Comment by ElectroGamesDev** [comment]
BankUI is now updated to API 4
