### ISSUE TITLE
Server Crash On Deposit 

### ISSUE THREAD

**Issue by dadevguy** [ElectroGamesYT/BankUI#18]
Please fix Server Crashes On Deposit

**Comment by ElectroGamesDev** [comment]
This will be fixed in the next update with BedrockEconomy support.

**Comment by dadevguy** [comment]
K When is Next update Waiting !!!

**Comment by dadevguy** [comment]
Hey pleas Update plugin

**Comment by dadevguy** [comment]
@ElectroGamesYT  Please Update This Plugin And Fix Crashes

**Comment by ElectroGamesDev** [comment]
This will be fixed today.

**Comment by dadevguy** [comment]
THanks

**Comment by ElectroGamesDev** [comment]
The update is live!
Until it gets approved, you can download it from here; https://poggit.pmmp.io/r/176036/BankUI_dev-66.phar
