### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by dadevguy** [ElectroGamesYT/BankUI#19]
Please Update Plugin To Bedrock Economy With Bug Fix

**Comment by PushkarOP** [comment]
🗿

**Comment by dadevguy** [comment]
Pushkar Here LoL

**Comment by ElectroGamesDev** [comment]
This will be added today! :D

**Comment by dadevguy** [comment]
WoW Thanks

**Comment by ElectroGamesDev** [comment]
The update is live!
Until it gets approved, you can download it from here; https://poggit.pmmp.io/r/176036/BankUI_dev-66.phar
