### ISSUE TITLE
Add Bedrock Economy Pleassssssssssssse UWU

### ISSUE THREAD

**Issue by kimbunner** [ElectroGamesYT/BankUI#20]
Um Hi Can You Add Bedrockeconomy Please

**Comment by dadevguy** [comment]
yea

**Comment by ElectroGamesDev** [comment]
This will be added today! :D

**Comment by dadevguy** [comment]
Wow Thanks, Again :)

**Comment by ElectroGamesDev** [comment]
> Wow Thanks, Again :)

The update is taking a bit longer than expected. It should be released today or tomorrow.

**Comment by dadevguy** [comment]
Okie :)

**Comment by ElectroGamesDev** [comment]
The update is live!
Until it gets approved, you can download it from here; https://poggit.pmmp.io/r/176036/BankUI_dev-66.phar
