### ISSUE TITLE
Pls add EconomyAPI 

### ISSUE THREAD

**Issue by ZippingBoat9588** [ElectroGamesYT/BankUI#21]
Yeah i have to use EconomyAPI because i have Other Plugins they need EconomyAPI so pls add it @ElectroGamesYT

**Comment by ElectroGamesDev** [comment]
EconomyAPI was removed in the recent versions and will not be re-added.

**Comment by ElectroGamesDev** [comment]
And please do not use this plugin until I fix it up today or tomorrow.
