### ISSUE TITLE
Economy 

### ISSUE THREAD

**Issue by Wengareki** [ElectroGamesYT/BankUI#24]
![Screenshot_20221030-195318_Chrome](https://user-images.githubusercontent.com/116268141/198883846-82746363-e6ad-4c62-a92d-5defe7452ac0.jpg)
ADD FOR ECONOMYAPI ALSO PLEASE.

**Comment by ElectroGamesDev** [comment]
Unfortunately EconomyAPI support will be not be re-added. It was removed for a reason and you shouldn't be using that plugin anymore.
