### ISSUE TITLE
Undified array key

### ISSUE THREAD

**Issue by Kybomaster** [ElectroGamesYT/BankUI#25]
when I used /bank I got an error "Undidied array key 'mynickname' in BankUI at line 869"

**Comment by ElectroGamesDev** [comment]
By any chance do you know what you were doing when this error occurred?

**Comment by Amitminer** [comment]
Error: Undefined array key "Amitminer"
File: plugins/BankUI/src/Electro/BankUI/BankUI
Line: 869
Type: ErrorException
Backtrace:
#0 plugins/BankUI/src/Electro/BankUI/BankUI(869): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[31] Undefined array key "Amitminer", string[60] /home/container/plugins/BankUI/src/Electro/BankUI/BankUI.php, int 869)
#1 plugins/BankUI/src/Electro/BankUI/BankUI(361): Electro\BankUI\BankUI->getMoney(string[9] Amitminer)
#2

**Comment by ElectroGamesDev** [comment]
Strange

**Comment by ElectroGamesDev** [comment]
This should be fixed in the latest BankUI version.
