### ISSUE TITLE
Crash /bank

### ISSUE THREAD

**Issue by NdaruAjaa** [ElectroGamesYT/BankUI#27]
PocketMine-MP version: 4.20.1 [Protocol 582]
Git commit: fea820a99e3fba8c91c0dc770fdef502ff8a6517
PHP version: 8.0.27
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BankUI

Error: Undefined array key "ImNdaru"
File: plugins/BankUI.phar/src/Electro/BankUI/BankUI
Line: 869
Type: ErrorException
Backtrace:
#0 plugins/BankUI.phar/src/Electro/BankUI/BankUI(869): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[29] Undefined array key "ImNdaru", string[72] phar:///home/container/plugins/BankUI.phar/src/Electro/BankUI/BankUI.php, int 869)
#1 plugins/BankUI.phar/src/Electro/BankUI/BankUI(361): Electro\BankUI\BankUI->getMoney(string[7] ImNdaru)
#2 plugins/BankUI.phar/src/Electro/BankUI/BankUI(256): Electro\BankUI\BankUI->bankForm(object pocketmine\player\Player#1161237)
#3 pmsrc/src/command/PluginCommand(50): Electro\BankUI\BankUI->onCommand(object pocketmine\player\Player#1161237, object pocketmine\command\PluginCommand#25993, string[4] bank, array[0])
#4 pmsrc/src/command/SimpleCommandMap(205): pocketmine\command\PluginCommand->execute(object pocketmine\player\Player#1161237, string[4] bank, array[0])
#5 pmsrc/src/Server(1422): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#1161237, string[4] bank)
#6 pmsrc/src/player/Player(1509): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#1161237, string[4] bank)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(823): pocketmine\player\Player->chat(string[5] /bank)
#8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#1185237)
#9 pmsrc/src/network/mcpe/NetworkSession(434): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#1182281)
#10 pmsrc/src/network/mcpe/NetworkSession(378): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#1185237, string[27] M./bank.XObG.Q..T.G.E.1...B)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(198): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[30] ..e.OJ..f..Or_.(.(d......N..'.)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[39] ....(..(3J.]g&..]..D....X./.9.......a..)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#1160105)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#17 pmsrc/src/Server(1681): pocketmine\snooze\SleeperHandler->sleepUntil(float 1682912041.2058)
#18 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#20 pmsrc/src/PocketMine(362): pocketmine\server()
#21 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by ElectroGamesDev** [comment]
This should be fixed in the latest BankUI version.
