### ISSUE TITLE
Users can dupe (duplicate) money, withdraw custom doesn't seem to work

### ISSUE THREAD

**Issue by TrinitroToluen0** [ElectroGamesYT/BankUI#30]
To reproduce:
1. Get some money (e.g 100)
2. Do /bank
3. Deposit all your money
4. Click "Withdraw custom"
5. Type any amount equal or lower than your bank's money amount (e.g if you have 200 in your bank, type 200 or lower)
6. See how your bank account dont loses any coin while you have 100% of the money of your bank account in your hand
7. Repeat the process and become millionaire

Demonstration: See how i started with $100 and ended up with $3200

https://github.com/ElectroGamesDev/BankUI/assets/92131917/deda380f-b340-469a-a4fc-038c7bd0482f

**Comment by ElectroGamesDev** [comment]
This is fixed in the latest version. Thank you
