### ISSUE TITLE
[Dupe] Able to Dupe Very Small Amounts of Money

### ISSUE THREAD

**Issue by Yandura** [ElectroGamesYT/BankUI#4]
How to reproduce the issue:
When depositing, sending, or withdrawing money, you can type in $0.999 and it will round it up to $1.

How to fix?:
Make it only accept int rather than float when typing in amounts.

**Comment by ElectroGamesDev** [comment]
This issue was fixed in the latest version. Please download the Dev Versions until a Poggit mod reviews the updated version.
