### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by jaylac2000** [ElectroGamesYT/BankUI#5]
- add /bankbal (player) to see a players balance in their bank. - maybe make it have a op perm for those servers that want only staff with the command access

- add /addbank (player) (amount) to allow staff to give money to someone directly in their bank

- maybe make bank balances store in a .json file instead of .yml files per player with money in their bank

**Comment by jaylac2000** [comment]
nevermind about the .yml to .json i just noticed how you got it setup

**Comment by ElectroGamesDev** [comment]
Hello. Thanks for the suggestion. We already have "/bank <Username>" so admins can view other player's bank Transaction Logs but I can forsure add these suggestions to it.

**Comment by physiciancoder** [comment]
Add a loan system, based on the players current balance. 
The player will not be able to take out a loan for more than 3 weeks, and not more than 200% of his existing balance when taking the loan. (eg. user with $100 in their balance cannot take more than $200 from the bank as a loan and the amount should be paid back in small sums starting after 5 days. with a % of interest ofc)

The loan can be taken from the user at appropriate timings and if the user does not have enough balance there will be warning given to the user and if still the amt is unpaid then ban xD

**Comment by ElectroGamesDev** [comment]
Nice idea but this feature won't be added. Its pretty much the same as /pay and Transfer Money.
