### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jaylac2000** [ElectroGamesYT/BankUI#6]
people get paid in interest 2 times in a row basically duplicating money

**Comment by ver24436** [comment]
Yes there seems to be an issue that only occurs sometimes. Players will receive a double payment of the interest daily. You can see in the images below

![image](https://user-images.githubusercontent.com/35013625/129321844-e7f91745-0707-4624-831e-c1c2d2792de7.png)

![image](https://user-images.githubusercontent.com/35013625/129321923-4a4a44e5-e95d-4dde-95fe-40bd75eecf26.png)

This problem magnifies the larger the balance is in the account, allowing players to earn a great deal of money depending on the servers economy.

It doesn't happen every day, it can go several days without this occurring, then sometimes it'll happen consecutive days.

This is happening with BankUI v1.0.2

**Comment by ElectroGamesDev** [comment]
I can forsure look into it when I have time. You can disable interest via config.yml until I get it fixed.

**Comment by ElectroGamesDev** [comment]
This bug may have been fixed in the latest release.
