### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by PushkarOP** [ElectroGamesYT/BankUI#7]
Add scorehud v6 support

**Comment by ElectroGamesYT** [comment]
I can forsure look into it.

**Comment by DrGuileDish1** [comment]
can you pls update it to 4.0.+

**Comment by ElectroGamesYT** [comment]
> can you pls update it to 4.0.+

Yes, I plan to soon.

**Comment by ElectroGamesYT** [comment]
The update is live with ScoreHud Support!
Until it gets approved, you can download it from here; https://poggit.pmmp.io/r/176036/BankUI_dev-66.phar
